[opener]
edit = [
    { run = 'nvim "$@"', block = true, desc = "Neovim" },
]

[open]
rules = [
    { mime = "*.json", use = "edit" },
    { mime = "application/json", use = "edit" },
    { mime = "text/*", use = "edit" },
]
